"""Guard against a stale Kaggle kit: fail if the bundled source drifts from the repo it was built from.

The kernel imports `celltrack`/`core` from the mounted `celltrack-kit` dataset, whose `celltrack_src/` copy
is gitignored and regenerated by `build_kit.py`. A partial or forgotten refresh (a surgical copy that misses
a file, a deleted module still present in the kit) surfaces only as a `ModuleNotFoundError` or, worse, a
silently older code path, hours into a hidden-eval run. This walks every `.py` under the repo's `celltrack`
and `core` packages and asserts a byte-identical twin exists in the kit — and that the kit carries no extra
`.py` the repo has since deleted. Run it before every `kaggle datasets version` / kernel submit; a non-zero
exit means rebuild the kit before shipping.
"""

from __future__ import annotations

import filecmp
import logging
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

_REPO = Path(__file__).resolve().parents[1]
_KIT_SRC = _REPO / "kaggle" / "kit" / "celltrack_src"
_PACKAGES = ("celltrack", "core")


def _sources(root: Path, package: str) -> dict[Path, Path]:
    """Every non-cache `.py` under `root/package`, keyed by its path relative to `root`."""
    base = root / package
    return {path.relative_to(root): path for path in base.rglob("*.py") if "__pycache__" not in path.parts}


def drift() -> list[str]:
    """Each way the kit's source diverges from the repo's — missing, changed, or orphaned files."""
    problems: list[str] = []
    for package in _PACKAGES:
        repo_files = _sources(_REPO, package)
        kit_files = _sources(_KIT_SRC, package)
        for relative, repo_path in repo_files.items():
            kit_path = _KIT_SRC / relative
            if not kit_path.exists():
                problems.append(f"missing from kit: {relative}")
            elif not filecmp.cmp(repo_path, kit_path, shallow=False):
                problems.append(f"stale in kit (differs from repo): {relative}")
        problems.extend(
            f"orphaned in kit (deleted from repo): {relative}" for relative in kit_files.keys() - repo_files.keys()
        )
    return problems


def main() -> None:
    """Report kit/repo source drift; exit non-zero so a submit workflow halts before shipping a stale kit."""
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    if not _KIT_SRC.exists():
        sys.exit(f"kit source absent: {_KIT_SRC} — run build_kit.py first")
    problems = drift()
    if problems:
        sys.exit("kit is stale — rebuild before submitting:\n  " + "\n  ".join(problems))
    logger.info("kit source matches repo (%s) — safe to submit", ", ".join(_PACKAGES))


if __name__ == "__main__":
    main()
