"""Which production modules nothing reaches — the orphan detector the other gates cannot be.

Every existing gate rewards a module for being *tested*, not for being *reached*: coverage counts lines a
test executes, vulture sees a symbol referenced (by that test), and the arch gates check the shape of the
import graph rather than whether anything enters it. Dead architecture accumulates in exactly that gap. One
audit found four orphans at once — a whole superseded epoch-loop design (`tracked_run`, `hparams`) plus a
crop sampler and a recall metric that later designs replaced — all of them green on every other check.

The walk is the honest definition of "used": start at the real entrypoints (a module defining `main`, so
`python -m` can run it, and anything the Kaggle kernels import) and follow the imports parsed from the source. What
is left over is reachable only from tests, which means the production path does not need it. That is a
finding to act on — wire it or delete it — not a failure to suppress.

    python -m tools.reachability            # list unreached modules
    python -m tools.reachability --assert    # exit 1 if any exist (once the list is empty)
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

_PACKAGES = ("celltrack", "core")
_KERNELS = Path("kaggle/kernels")  # NOT all of kaggle/: kit/ holds a generated COPY of the source, whose
# internal imports would register as entrypoints and mark every orphan it happens to mention as reachable.
_ENTRY_PATTERN = re.compile(r"^def main\(", re.M)
_KERNEL_IMPORT = re.compile(r"(?:from|import) ((?:celltrack|core)[\w.]*)")


class Reachability:
    """Parses the source's own imports, walks them from the real entrypoints, and reports what nothing reaches.

    The imports are read from the AST rather than from `docs/architecture/graph.json`: that artifact is
    regenerated by hand and was measurably missing real edges, and a reachability answer computed from a
    stale picture is worse than none — it marks live modules dead and dead ones live.
    """

    def __init__(self, root: Path) -> None:
        self.root = root
        self.modules = {
            self._module_name(path)
            for package in _PACKAGES
            for path in (root / package).rglob("*.py")
            if path.stem != "__init__"
        }
        self.imports = {module: self._imports_of(module) for module in self.modules}

    def _imports_of(self, module: str) -> set[str]:
        """The first-party modules `module` imports, resolved to the names in `self.modules`."""
        tree = ast.parse((self.root / Path(*module.split("."))).with_suffix(".py").read_text(encoding="utf-8"))
        targets: set[str] = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module:
                targets |= self._resolve(node.module)
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    targets |= self._resolve(alias.name)
        return targets

    def _resolve(self, dotted: str) -> set[str]:
        """`dotted` as a module we know, or the module it would be if the tail is a symbol inside one."""
        if dotted in self.modules:
            return {dotted}
        parent = dotted.rsplit(".", 1)[0]
        return {parent} if parent in self.modules else set()

    def entrypoints(self) -> set[str]:
        """Modules a human or a kernel actually starts: anything defining `main`, plus the kernels' imports.

        The Kaggle kernels are not part of the graphed packages but they import into them, so their imports
        are roots too — otherwise the whole submission path would read as unreachable.
        """
        found = {
            self._module_name(path)
            for package in _PACKAGES
            for path in (self.root / package).rglob("*.py")
            if _ENTRY_PATTERN.search(path.read_text(encoding="utf-8"))
        }
        kernels = "\n".join(f.read_text(encoding="utf-8") for f in (self.root / _KERNELS).rglob("*.py"))
        return (found | set(_KERNEL_IMPORT.findall(kernels))) & self.modules

    def unreached(self) -> list[str]:
        """Every module no entrypoint reaches — reachable only from tests, if at all."""
        reached = self.entrypoints()
        stack = list(reached)
        while stack:
            for target in self.imports.get(stack.pop(), ()):
                if target in self.modules and target not in reached:
                    reached.add(target)
                    stack.append(target)
        return sorted(self.modules - reached)

    def _module_name(self, path: Path) -> str:
        """The dotted module name of a source file, relative to the repo root."""
        return ".".join(path.relative_to(self.root).with_suffix("").parts)


def main() -> None:
    parser = argparse.ArgumentParser(description="Report production modules no entrypoint reaches.")
    parser.add_argument("--assert", dest="enforce", action="store_true", help="exit 1 if any module is unreached")
    arguments = parser.parse_args()
    orphans = Reachability(Path.cwd()).unreached()
    for orphan in orphans:
        print(f"unreached: {orphan}")  # noqa: T201 — a report CLI prints its report
    print(f"{len(orphans)} unreached module(s)")  # noqa: T201
    if arguments.enforce and orphans:
        sys.exit(1)


if __name__ == "__main__":
    main()
